language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  - "/client/node_modules"
deploy:
  provider: heroku
  api_key:
    secure: w9c9L7DO7hotrPy3qkIb/Im8b3u70dydZCVd41aA8s9nqH4qWe9DRQSxwx9QFWeBuDtQvxf524Kl+4eip/T9PfwJ8Rkp+HKH5vuZZ3c9OYNTOu7t9NGtaguaGeUSiTJ34CHHK2Y14M2xao3RUfaYpjLSAVkVYdr00HphvQhgIx3jL3P9YvMij4QDKbubjkXoiogW4ze7EVX+RdH3Lti8+xWPg6ZMVqwu87gahPeuZjw0DJofK2ULapEJTkhNnOLJETuhFLIoID/oCP4K0aWt7oLFRepBoYy/Mr/Tb78VPtWQ8XsnbyVrjWNYB+K1Ro1ZT+lU/G2SqcE/DhOSaPG9XF/1jMb6SMqOiBr78S+EDhwgiozwS5R2v8/nC4ce6IfTeq2STabq4Aw+xf2RaslLILdYmUhCxp3gaQX3YYj3t+hhdbgZMA+2JWqFQ2juV8gKvXFz6UJiBNsj9bwjUlN+aVC0t0YzVUHBNn4TggCFMx3siWFgm39xhhzG+acLTQU3HL6g9dIfarsc7K5bLWND74bvsytCQghDYrVhcXz+vafDibw9lSCYKrgkU5C3DiUhwMFAm+GLJEF/ynlnSSPCD6Pf/LW7pKpJJnHLIhAWYiwQZDXgqzeYmy/DylQIhdeJDbGlHEVhinsdaga+QwCBriSnDN6qzAcKjIteXHII1NY=
