language: node_js
cache:
  directories:
    - node_modules
    - /client/node_modules
deploy:
  provider: heroku
  api_key:
    secure: LscFIle6Gtz/4InuM4hjQcxzdplXr84VMGKGf83HoNyHwgMJ7GX/OkAKAIPNuKudUTzrer6L9lMcUHuqixgpmd36s4xPGtBHzy+CrAXCSMJGSJgD7IBcva5t3AruapKPQoUeuZsCXMEljQKrg+2G16UwP9v4odHJVbVZfm3fWhitfBb6Q2w0inbucukjVckpXQjodzWFUEY4vNYG9Q59AaxJMVX0OhbSvil1MR0o1rlNtiOObD1nbrwY4WAhkvoAhpxMi5kyN1B8MZvDc2ZPqjW7+WY5B+zyzAXb6ejOubRdwiOvfUaau6Tdx1p/RtWNA6OWMk0esrfHYjZPU3qOj5HEr9wtuDq3GMHPenKj8eGgaF3LuAEEsL25eP4seYE7RmmqZpgUSKxqXmHoi/3rFVF0EEKLrSK08aRMk/EQzL93DY2w1T7D+ag7ZUlylM9QSRFy0bmUkN1pmcOw9iJdv6Q2dw0ji5PP1odDxSudD1qb8NByQCRxX5QA3QvzpifY+UU9BQZs9Szne/4IqGs857t46yW1oeFjye5oqQXIDqtHd+TAEa+Bqo7m09G9bBStnG4lMVnyFX8lmpYM2c50MOqXRXCAT+TquyoblayQf9GG+unNXrufhuqRCHdkCsQ0LC/eUrhvyJ2kKWoa2BorTT7UYx6cNVwLa/YoySdDFXM=
