language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  - "/client/node_modules"
deploy:
  provider: heroku
  api_key:
    secure: rt+8vqeJ0WuoJd6gdQjSmZmODgkQGM6d2QVuHHmrSkDLY80ZtWf5hcHLA6mfxg0nUMJraZZrXfI7x599BWj4oo9HTLgJylSTpcJovrvsL08t5vsBpmFlFVB5fly+0xHMEYLWxXLUpzY2RdgMD1gSMUNucKmv0/1taiRasX7HaulLbwXFiyZPjZyhfPRk9kL2FHLeTLxF/5lREV/oFJraZi85PiBYArtC1jhzuF57smyvoIDwVU3O/vm7DbE55qtbK5pcB3y/cEVXW5nLsKyONM/Af/6HiVv264ugijYhavIR3rFMpeGLpdSaFrgNvIuKDvPYO6NByUd57ER4Uv2Evl4zfvaPEwBD7mVvxOttfn2TsBPPy7wO9O2iWRf/GbRUsDKhvdTz9GTr/c3HfEkRh9ZPGomCWwfT1LZr6qu+jw271UZg7ns852ih5jHlvqo/145OTIaFvI98SNm23D94GyJw5nHcxbiYcWi20of/DTJPf0AqUmJiY201s4ETvmDTy5UIcKbYgaUcS3jWLIVmSs35qV372RoJRnR0bRkpMk8UQS4HEX1VTYyElnccr4JrN0HU3ZQ12VD/9eSg0ovuXOcwNd2lt/ywmpDX8q5b2a88FAnsnDO2YKfvwMgNXnzmt7KGXaCG4dkcxoOACwCc1+XrMstiBu48eXrsGovKuN8=